### ISSUE TITLE
Minor improvements suggestions (tested on ubuntu 19 10

### ISSUE THREAD

**Issue by blue-devil-93** [B00merang-Project/Windows-7#1]
Hi, 
first of all you have a very impressive amount of themes. Your code seems to be a wondefully written scss. It looks fantastic. This theme is a very good one. Feels very nostalgic and clean. 
On 19.10 mate i could find a few minor things i found :

toolbar/headerbar bottom border: is too big-/wider than it should. Using bg 90% and then dark color is a very unclean way to implement it. Maybe did this error  myself before )=.
You could use  an asset or better:
border-bottom-color: $borders_color;
box-shadow-inset: # The one you use in # bottom. 
I am aware this will add a light 1 px border on top and on the sides too but this might be a feature considering p.ex eye of mate.

Panel: the indicator is to light set the bg to transparent.

caja-desktp: Hope you see it yourself.
Where is the original scss code then i could suggest you the changes myself.

The handle png`s do  looks blurred when used on with nvdidia cards. don`t know why.

I do really enjoy using this theme. Almost stops me from writhing themes as good as its written. You did a very good work.

very kind regards 
blue-devil-93

**Comment by blue-devil-93** [comment]
![minor-thingls](https://user-images.githubusercontent.com/59343188/75606161-edae8380-5ae1-11ea-8860-f176edc2cc70.png)

**Comment by Elbullazul** [comment]
hello, thank you for the feedback. Glad you're liking our themes!

> - [ ] toolbar/headerbar bottom border: is too big-/wider than it should.

haven't noticed. I'll patch it once I find some time

> - [ ] Panel: the indicator is to light set the bg to transparent.

having some problems lately with xfce panel. hopefully can correct soon

> - [ ] caja-desktp: Hope you see it yourself.

noted

- [ ] The handle pngs do looks blurred when used on with nvdidia cards. dont know why.

> - I added gtkscale support (double resolution for hidpi screens), maybe it's related?

SCSS is maintained separately: https://github.com/B00merang-Project/Azurra_framework

**Comment by blue-devil-93** [comment]
Which version of xfce panel do you use?  Thx for the link to the scss Folder. If i have time then i can use github to submit merge requests you can look at then and decide if they work for you or not.

**Comment by blue-devil-93** [comment]
Installed ubuntu mate  20.04 in a virtualbox. Send you a working mate panel
scss next days. Can't test fully if it does interfere with xfce panel. Try
to code it as much as possibly only against mate panel. Have ubuntu Studio
19.?? Ubuntu mate 18.10, 19.10 and 20.04.

Found the azurra framework.
The script does not work completly on my system (sass missing) but got the
code compiled to a css using sassc.

So in future can send you more concrete code suggestions.

**Comment by Elbullazul** [comment]
@blue-devil-93 I normally test on the latest xfce release. That would be 4.14 I think?

never tested on ubuntu studio, generally on linux mint mate or ubuntu mate. The last check I did was on 19.10 I think

it needs the ruby-sass package, but you can install it with `sudo apt install sass`.

I'd recommend that you use the built-in script to compile as it also does some other things (I documented a bit how it works in [the wiki](https://github.com/Elbullazul/Azurra_framework/wiki))

**Comment by blue-devil-93** [comment]
[_mate-panel.scss.txt](https://github.com/B00merang-Project/Windows-7/files/4286944/_mate-panel.scss.txt)

**Comment by blue-devil-93** [comment]
A panel only scss file using transparency and nearly all posssible theme hacks

**Comment by Elbullazul** [comment]
can you post a screenshot of the impact of the suggestions?

**Comment by blue-devil-93** [comment]
![themepreview](https://user-images.githubusercontent.com/59343188/75916650-06f45e80-5e59-11ea-9146-65a00d864e81.png)

A screenshot of what this scss does. There is of course the possibility to use a png asset for panel, the way i use it. And the panel base color can be desaturated.

**Comment by Elbullazul** [comment]
looks pretty clean. I don't remember why I didn't use an image (there is one in the cinnamon folder) but remember some problems with the tray buttons.

also, isn't the calendar portion supposed to be transparent as well?

**Comment by blue-devil-93** [comment]
My suggested scss file does theme mate panel while not relating on the main
gtk theme definitons or assets. You could use it p.ex on win10 of azurra
framework and it would look and work the same.

If i remember correctly you could use a asset as an border image for button.
Vista-ish black buttons are easily doable using a horizontal scss gradient.
Maybe its possible to use a vertical and-/or radial gradient for the panel
button. Check that tommorow.
The overall panel background is possible as image in cinnamon but not in
mate as far as i know if defined theme wise. It was in gnome-flashback. The
button radius needs to be increased a bit.

Yes the calender button needs to be transparent. Patch that soon.

**Comment by blue-devil-93** [comment]
![panel_new](https://user-images.githubusercontent.com/59343188/75980806-7b73df80-5ee3-11ea-9ea1-bdbf523f2dc9.png)

Installed  ruby-sass, now the azurra script works fine .

![panel_new](https://user-images.githubusercontent.com/59343188/75980874-99d9db00-5ee3-11ea-9791-a9061f99f1e5.png)
[_mate-panel.scss.txt](https://github.com/B00merang-Project/Windows-7/files/4292876/_mate-panel.scss.txt)

**Comment by Elbullazul** [comment]
I'll try to make some time this weekend to have a look at your patch. I must say it looks very good!

**Comment by blue-devil-93** [comment]
Things i use for gtk3 theming are:
env GTK_DEBUG=interactive application
sublime text
meld
Gimp,inkscape
terminal(sakure,mate-).

The coding stuff i do in a configured and themed icewm inside virtualbox.
Just because it doesn't crash that easily.
And then test if it works  in mate etc.

Glad you like it. Your closest similar part in the theme is the mate
"mixing" in the file _environments.css. Can send you a black  vista-aero
version too.

**Comment by Elbullazul** [comment]
I'll try and implement it this afternoon. Vista style would be cool, please attach a screenshot as well. Can you do the changes on the Vista GTK theme? It has some differences with Aero I believe

**Comment by blue-devil-93** [comment]
[_environments_vista.scss.txt](https://github.com/B00merang-Project/Windows-7/files/4313771/_environments_vista.scss.txt)
![panelbg](https://user-images.githubusercontent.com/59343188/76339275-24fb0c80-62fa-11ea-9ac2-b5879b0e883c.png)

**Comment by blue-devil-93** [comment]
![screenshot](https://user-images.githubusercontent.com/59343188/76339642-aa7ebc80-62fa-11ea-8e9a-89e4d6a125a4.png)

**Comment by blue-devil-93** [comment]
I could try to load the image as an border. However setting the panel bg  image is quickly done  in mate and doesn`t break vertical borders. The bottom variant is default and the ttop if xou set manually an bg image.

**Comment by Elbullazul** [comment]
f720f16 adds proper support for MATE panel.

still working on desktop icon labels issue

**Comment by Elbullazul** [comment]
781fd473bd19a5e02dec80d02f39f9c7299e880d fixes this
![image](https://user-images.githubusercontent.com/15310985/100400806-b72c7780-3025-11eb-88ec-dc1715d7d811.png)
