### ISSUE TITLE
This theme will not look as intended because the required GTK+ theme 'Windows 7' is not installed.

### ISSUE THREAD

**Issue by Xopek-Endurance** [B00merang-Project/Windows-7#10]
Hello! I have a problem with Windows 7 theme

I have Ubuntu Mate 22.04 , GTK + 3.24.33
And I installed gtk2-engines-murrine and gtk2-engines-pixbuf 

When I install theme to /user/home/.themes and select it from Apperance, i recieve message "This theme will not look as intended because the required GTK+ theme 'Windows 7' is not installed."
![Screenshot at 2022-08-31 15-13-02](https://user-images.githubusercontent.com/108617048/187678138-365387e3-35ed-4c0a-858e-9519ad9d82be.png)

**Comment by Elbullazul** [comment]
b2e775ff32193c7551dc9a02727dc53f4a96b086 may fix this issue, can you confirm?

**Comment by Xopek-Endurance** [comment]
I replaced file index.theme to https://github.com/B00merang-Project/Windows-7/commit/b2e775ff32193c7551dc9a02727dc53f4a96b086 , but issue remains

**Comment by Elbullazul** [comment]
That's weird. I'll have a deeper look at it when I have time

**Comment by Elbullazul** [comment]
so I tried the latest fix, and I get this:
![image](https://user-images.githubusercontent.com/15310985/188949025-4acb679d-0173-4fa9-bda8-9c633bbe3984.png)

are you sure the error you're getting is still `the required GTK+ theme is not installed`?

**Comment by Xopek-Endurance** [comment]
I installed Icon Theme from Your Site. Issue remains. I renamed folder of Windows Theme from "Windows-7-2.1" How it names in Your archive to "Windows 7" How it names in index.theme, and i renamed folder ow Icon Theme from "Windows-7-master"  How it names in Your archive to "Win2-7 6.0" How it names in index.theme of Icon Theme. 
![Screenshot at 2022-09-07 22-18-06](https://user-images.githubusercontent.com/108617048/188961013-3aed7ee2-5071-4b3c-af49-a21bbc0bd7e6.png)

Now It work without error messages, but with visual problems, for example - not changins Menu Icon and I cannot see any checkboxes - all on screenshot

**Comment by Elbullazul** [comment]
Try renaming the theme folder to `Windows-7`, and the icon theme to `Windows-7` too (it doesn't matter if they have the same name, the icons are in another folder)

I think this should fix that

**Comment by Xopek-Endurance** [comment]
I renamed both themes to "Windows-7" and edited their "index.theme"s. Issue from previous post remains

**Comment by Xopek-Endurance** [comment]
I solved by myself problem with Menu Icon! I checked other Mate theme - in there theme Menu Icon in folder: $themename/scalable/places , and named "start-here-symbolic.svg" - and I opened Windows 7 theme folder, found file /.icons/Windows-7/apps/gnome-about-logo.png , moved it to /.icons/Windows-7/scalable/places (There are no there folders, I created them) and renamed file to "start-here-symbolic.png" After this Menu Icon work!!! 
![Screenshot at 2022-09-25 15-24-28](https://user-images.githubusercontent.com/108617048/192143317-ee9f857e-f042-4704-89ad-de84ae015ce1.png)

**Comment by Elbullazul** [comment]
nice! thanks for posting the solution :D
