### ISSUE TITLE
Not working on pop_os?

### ISSUE THREAD

**Issue by MicrowavedSquirrel** [B00merang-Project/Windows-7#18]
I tried to use this on pop_os using tweaks + the user themes extensions and all it does is change the top bar clear.. Did I do something wrong or does it just not work on pop_os?
![image](https://github.com/user-attachments/assets/23c5c760-1a05-4b6b-a83d-aa27bdbd2181)

(edit was adding the image)

**Comment by MicrowavedSquirrel** [comment]
Well, it seems I forgot to add the icons.. ect, but It still doesn't look right
![image](https://github.com/user-attachments/assets/d1e24e06-2460-44e6-822d-c4d45930cbe3)

**Comment by Elbullazul** [comment]
You have to change the application theme (first drop down)

**Comment by MicrowavedSquirrel** [comment]
> You have to change the application theme (first drop down)

yes,,, thank you.. i also forgot to enable the dash to panel extension, which fixed the look of it.. any idea on how to change the cursor?

**Comment by Elbullazul** [comment]
The second combobox changes that. You can use [this theme](https://www.pling.com/p/999972) for that
