### ISSUE TITLE
Screenshot link dead

### ISSUE THREAD

**Issue by lynrayy** [B00merang-Project/Windows-7#19]
Screenshot in readme not working because of link rot
![image](https://github.com/user-attachments/assets/5fde2144-0dc5-479e-9c51-39e36c92e775)

**Comment by jacko-png** [comment]
I noticed this too. I believe I've seen the asset around though.

**Comment by jacko-png** [comment]
I followed https://b00merang.weebly.com. It seems like b00merang now uses https://b00merang-project.github.io.

Here's a page with all the Windows pictures:
https://b00merang-project.github.io/windows

**Comment by Elbullazul** [comment]
Fixed, thank you for letting me know.
