### ISSUE TITLE
Sidebar icons in file manager(nemo) has basic icons

### ISSUE THREAD

**Issue by akash-258** [B00merang-Project/Windows-7#4]
I just tried windows_8 and windows_7 icons in cinnamon and found that win8 icons have good sidebar mini icons in file manager whereas win7 has basic black_&_white icons. But win8 icons are not supported and buggy when changing volume so I cant use those.
Is there a way to make sidebar using win7 icons look like win8.
win7 : https://ibb.co/hc85vRZ
win8 : https://ibb.co/0yKNnRX

**Comment by Elbullazul** [comment]
It's possible to have sidebar icons in the Win7 theme, but it requires some work

also, you should submit icon related issues to the dedicated icon repo: https://github.com/B00merang-Artwork/Windows-7

**Comment by akash-258** [comment]
Ok thanks, I will submit my problem there.
