### ISSUE TITLE
There is a more accurate theme you could base this one off of.

### ISSUE THREAD

**Issue by Shadowblitz16** [B00merang-Project/Windows-7#7]
here is a more accurate theme to windows 7 https://www.opendesktop.org/p/1014539
however it doesn't support gtk 3 and 4 maybe you could download it and convert it to gtk 3 and 4?

**Comment by Elbullazul** [comment]
sorry, bug GTK2 themes can't be migrated easy to GTK3. If you want to suggest improvements, feel free to suggest them in a separate issue
